### ISSUE TITLE
When 0 guilds, Guilds tab shows Available: NaN

### ISSUE THREAD

**Issue by markszpak** [KnowledgeGarden/TQPortal#2]
Issues app, under Guilds tab, shows NaN available Guilds when no guilds have been created.

**Comment by allenbyerly** [comment]
Hey KnowledgeGarden/TQPortal,

I have the opportunity to vouch for (recommend) people to join FounderDating, the invite-only network for cofounders, advisors, and startups. You're on my short list. There are amazing people in the network. I highly recommend applying, no matter what stage you're in.
Apply here > http://members.founderdating.com/connect/?frvche=1056633&s=sidebar

Check it out,
AllenTo unsubscribe from all FounderDating emails click here: http://mail.founderdating.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcXPHdFO4obCvgFrneOYjUh7rCB-2FtOqtd-2FmFCIvERbgv1RZxSWxCgrTt9ZEjsFpc23ppz-2BaI2O6wLRKmfyvX4BzWaX8QKVmS0lPxEKHZB-2Bi8P7oawO8g41X2F2GxC-2FGwVc4jjB-2BqFHt6OrhFaSJCPIacSLlyG-2BAlZekEw8Ax16jMCuHdLRbdzcpWJs58V7qNcdD0ADmSr1fwxCWy-2BCRbB6hUiRkoSDvyUJg4A6hONsGRMLXj2Xmk3FcE-2BuE5WhV7PkZjveYhqpd9Z7WHANVQtbOpEmy8sNOYfgkNHCmu5QaRUIbanN-2Fz-2Foa3FUwPSkb1i2LtfQDQWNDCv2MxW8NMxaeNO049sXr5D6YFqdmJ8r9HJ.
